apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-config
data:
  JAVA_OPTS: "-server -Ddebug -Xmx1g -Xms1g"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-mysql-config
data:
  MYSQL_URL: "jdbc:mysql://mysql:3306/tododb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8"
  MYSQL_USERNAME: "root"
---
apiVersion: v1
kind: Secret
metadata:
  name: todo-mysql-secret
type: Opaque
data:
  MYSQL_PASSWORD: cGFzc3dvcmQ=